# Assembler executable
ASM = avra

# Directory configuration
SRC_DIR = src

# Main source and target files
MAIN_ASM = main.asm
TARGET_HEX = $(SRC_DIR)/main.hex

# List all assembly (.asm) and include (.inc) files as dependencies
DEPS = $(shell find $(SRC_DIR) -type f \( -name "*.asm" -o -name "*.inc" \))

# Intermediary files generated by avra that are not needed after compilation
INTERMEDIATE_PATTERNS = *.obj *.eep.hex *.eep *.cof *.lst
INTERMEDIATES = $(addprefix $(SRC_DIR)/, $(INTERMEDIATE_PATTERNS))

.PHONY: all compile clean

# Default target
all: compile

# Compile target: builds the hex file and automatically removes intermediary files
compile: $(TARGET_HEX)

$(TARGET_HEX): $(DEPS)
	@echo "Assembling $(MAIN_ASM)..."
	cd $(SRC_DIR) && $(ASM) $(MAIN_ASM)
	@echo "Removing intermediary files..."
	rm -f $(INTERMEDIATES)
	@echo "Compilation successful. Output: $(TARGET_HEX)"

# Clean target: removes the target hex file and any remaining intermediary files
clean:
	@echo "Cleaning build files..."
	rm -f $(TARGET_HEX) $(INTERMEDIATES)

# Detecta automaticamente a porta USB/ACM conectada (ou cai de volta para /dev/ttyUSB0)
DETECTED_PORT = $(shell ls /dev/ttyUSB* /dev/ttyACM* 2>/dev/null | head -n 1)
PORT ?= $(if $(DETECTED_PORT),$(DETECTED_PORT),/dev/ttyUSB0)
BAUD ?= 115200

upload: compile
	@echo "Usando a porta: $(PORT)"
	avrdude -v -p atmega328p -c arduino -P $(PORT) -b $(BAUD) -U flash:w:$(TARGET_HEX):i
